apiVersion: v1
kind: Service
metadata:
  name: struts2app-service
spec:
  selector:
    app: struts2app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080 # must be in the default range of 30000-32767
  type: NodePort